### ISSUE TITLE
Can't open the Youtube Channel link.

### ISSUE THREAD

**Issue by Lafcadia** [ZigaoWang/ZigaoWang#12]
![image](https://github.com/ZigaoWang/ZigaoWang/assets/147896059/ff89acc5-434d-4df8-8fce-78c972c0cb8a)

![image](https://github.com/ZigaoWang/ZigaoWang/assets/147896059/907d3898-901c-40fb-9426-997932e41266)

You may try to replace it with this one: https://www.youtube.com/@zigaow.

BTW, great content, both the channel and the blog.

**Comment by ZigaoWang** [comment]
Thank you so much for spotting out!

**Comment by ZigaoWang** [comment]
Fixed it, again, thank you so much!

**Comment by ZigaoWang** [comment]
你是中国人？你在杭州？我在上海

**Comment by Lafcadia** [comment]
> 你是中国人？你在杭州？我在上海

我是杭州人。

**Comment by ZigaoWang** [comment]
很高兴认识你！

**Comment by Lafcadia** [comment]
> 很高兴认识你！

加个微信或者Q？(doge)

**Comment by Lafcadia** [comment]
> > 很高兴认识你！
> 
> 加个微信或者Q？(doge)

我之前给你发了封邮件owo

**Comment by ZigaoWang** [comment]
你几岁了呀

**Comment by ZigaoWang** [comment]
okkkk 我加你？

**Comment by Lafcadia** [comment]
> 你几岁了呀

高一。

**Comment by Lafcadia** [comment]
> okkkk 我加你？

你发我邮箱吧。

**Comment by ZigaoWang** [comment]
微信号邮箱发你了

**Comment by ZigaoWang** [comment]
我七年级

**Comment by Lafcadia** [comment]
i see, thanks
